server:  
  port: ${PORT:9999}

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: lecom
    driver-class-name: com.mysql.cj.jdbc.Driver